version: '3.8'

services:
  frontend:
    build: .
    container_name: frontend
    environment:
      VITE_BASE_URL: ${VITE_BASE_URL}

  backend:
    image: davidjj76/nodepop-api
    container_name: backend
    ports:
      - ${PORT}:${PORT}
    restart: unless-stopped
    volumes:
      - nodepop-api-data:/home/node/app/data
      - nodepop-api-uploads:/home/node/app/${UPLOADS_FOLDER}

  db:
    image: mongo:7.0.5
    restart: always
    ports:
      - '27017:27017'
    container_name: nodepop-adv-db
    volumes:
      - mongo:/data/db

  nodepop-adv:
    depends_on:
      - db
    image: practica-node-avanzado-app
    container_name: nodepop
    ports:
      - 3000:3000
    restart: always
    environment:
      PORT: 3000
      MONGO_URL: mongodb://nodepop-adv-db
      MONGO_DB_NAME: nodepop-adv
      JWT_SEED: 3iCYK0EPSbrRKryYlrw3boVtgp1Rx1RS0TY8IAMYGuk7eil8YmhuOcT5MpzBaJR
      PUBLIC_FOLDER: public
      UPLOADS_FOLDER: uploads

  thumbnail:
    depends_on:
      - nodepop-adv
    image: practica-node-avanzado-thumbnail
    container_name: thumbnail

  proxy:
    build: ./nginx
    container_name: proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./nginx/passwd/:/etc/nginx/passwd
      - ./nginx/letsencrypt/:/etc/letsencrypt/
      - ./nginx/certificates/certs/:/etc/nginx/certs
      - ./nginx/certificates/private/:/etc/nginx/private
      - ./nginx/logs/:/var/log/nginx/

volumes:
  nodepop-api-data:
  nodepop-api-uploads:
